### ISSUE TITLE
make the instance view shrink when chips overflow

### ISSUE THREAD

**Issue by erica-w-fu** [zeno-ml/zenoml.com#5]
Currently the instance view is simply pushed down when the chips overflow. Instead, the chips should take over more vertical space and the instance view should shrink.

Normal sizing
![image](https://user-images.githubusercontent.com/72369224/204947967-66a0024d-de70-482d-a0cc-3746c940fa63.png)

Overflow sizing
![image](https://user-images.githubusercontent.com/72369224/204947988-4a5a9d2e-483a-4e03-9e6d-c0f19afdf921.png)

**Comment by cabreraalex** [comment]
@erica-w-fu can you move this to the zeno repo
